version: '3.6'
services:
  iris:
    build: 
      context: iris
      dockerfile: dockerfile
    restart: always
    ports: 
      - 52773:52773
    volumes:
      - ./iris/:/irisdev/app
      - ./data/:/tmp/data
  r:
    build: 
      context: r
      dockerfile: dockerfile
    restart: always
    ports:
      - 6311:6311
    volumes:
      - ./r/:/tmp/r
      - ./data/:/tmp/data