FROM openjdk:8u252-jre

ENV GWDIR /jgw
ENV PORT 55554
ENV ISC_PACKAGE_INSTALLDIR /usr/irissys
ENV ISC_JARDIR $ISC_PACKAGE_INSTALLDIR/dev/java/lib/JDK18

COPY --from=store/intersystems/iris-ml-community:latest \
      $ISC_JARDIR/intersystems-jdbc-3.2.0.jar \
      $ISC_JARDIR/intersystems-utils-3.2.0.jar \
      $ISC_JARDIR/intersystems-rgateway-3.2.0.jar \
      $GWDIR/

CMD java $JVMARGS -Xrs -classpath "$GWDIR/*" com.intersystems.gateway.JavaGateway $PORT "" "R Remote" "0.0.0.0" 2>&1
