
FROM ubuntu:18.04

ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
	openjdk-8-jdk \
	nano \
    r-base 

ENV GWDIR /jgw
ENV PORT 55554
ENV ISC_PACKAGE_INSTALLDIR /usr/irissys
ENV ISC_JARDIR $ISC_PACKAGE_INSTALLDIR/dev/java/lib/JDK18

COPY --from=store/intersystems/iris-ml-community:2021.1.0.215.0 \
      $ISC_JARDIR/intersystems-jdbc-3.2.0.jar \
      $ISC_JARDIR/intersystems-utils-3.2.0.jar \
      $ISC_JARDIR/intersystems-rgateway-3.2.0.jar \
      $GWDIR/

COPY . /r

CMD ["/bin/bash", "/r/start.sh"]

EXPOSE $PORT 6311
